ServerTokens Prod
ServerSignature Off

<Directory /var/www/html>
    Options -Indexes
    AllowOverride None
    Require all granted
</Directory>

SetEnvIf Request_URI "^/api/" no-gzip=1

<LocationMatch "^/service-worker\.js$">
    Header always set Cache-Control "no-cache, max-age=0, must-revalidate"
</LocationMatch>
